[gcp_service_account]
type = "service_account"
project_id = "leafy-unity-469117-c2"
private_key_id = "41ad9507be2a97ec605d18013ec470b31751831e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCVUDrQxZwwmB2p
... full key block here ...
-----END PRIVATE KEY-----"""
client_email = "streamlit-leaderboard@leafy-unity-469117-c2.iam.gserviceaccount.com"
client_id = "115981455553110264285"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-leaderboard%40leafy-unity-469117-c2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
